#21 Access token is sent with every http request.
w0l1d/TalibHub pull request #25
Opened 2023-12-22 16:42 UTC by YASSINEJR3

- Acess token is added to every http request using Interceptor
- when Acess Token is Expired, it request for a new one using refresh token
- CORS Configuration is added in the Security config because it's important to be able to accept http requests from angular app

2023-12-22 17:38 UTC, AbdoAitrais requested changes
try to use a Token object instead of any

2023-12-23 09:59 UTC, w0l1d approved these changes, later dismissed

2023-12-23 10:10 UTC, KABILA-Anas approved these changes, later dismissed

2023-12-23 10:36 UTC, AbdoAitrais approved these changes, later dismissed
Nice Good job guys

2023-12-23 10:46 UTC, w0l1d submitted a review, later dismissed

2023-12-23 11:11 UTC, w0l1d approved these changes

2023-12-23 11:12 UTC, KABILA-Anas approved these changes

2023-12-23 11:12 UTC, merged